# yaml-language-server: $schema=../../schemas/dsomm-schema-information-gathering.json
---
Information Gathering:
  Logging:
    Centralized application logging:
      uuid: fe875e17-ae4a-45f8-a359-244aa4fcbc04
      risk:
        Local stored logs can be unauthorized manipulated by attackers with system
        access or might be corrupt after an incident. In addition, it is hard to perform
        an correlation of logs. This leads attacks, which can be performed silently.
      measure:
        A centralized logging system is used and applications logs (including
        application exceptions) are shipped to it.
      difficultyOfImplementation:
        knowledge: 1
        time: 1
        resources: 1
      usefulness: 5
      level: 3
      dependsOn:
        - Alerting
      implementation: []
      references:
        samm2:
          - O-IM-A-1
        iso27001-2017:
          - Not explicitly covered by ISO 27001 - too specific
          - 12.4.1
        iso27001-2022:
          - Not explicitly covered by ISO 27001 - too specific
          - 8.15
    Centralized system logging:
      uuid: 4eced38a-7904-4c45-adb0-50b663065540
      risk:
        Local stored system logs can be unauthorized manipulated by attackers
        or might be corrupt after an incident. In addition, it is hard to perform
        a aggregation of logs.
      measure:
        By using centralized logging logs are protected against unauthorized
        modification.
      difficultyOfImplementation:
        knowledge: 1
        time: 1
        resources: 1
      usefulness: 2
      level: 1
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/rsyslog
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/logstash
      references:
        samm2:
          - O-IM-A-1
        iso27001-2017:
          - Not explicitly covered by ISO 27001 - too specific
          - 12.4.1
        iso27001-2022:
          - Not explicitly covered by ISO 27001 - too specific
          - 8.15
      isImplemented: false
      evidence: ""
      comments: ""
    Correlation of security events:
      uuid: ccf4561d-253f-4762-adcb-bc4622fd6fc5
      risk:
        Detection of security related events with hints on different systems/tools/metrics
        is not possible.
      measure:
        Events are correlated on one system. For example the correlation and
        visualization of failed login attempts combined with successful login attempts.
      difficultyOfImplementation:
        knowledge: 4
        time: 4
        resources: 4
      usefulness: 3
      level: 5
      dependsOn:
        - Visualized logging
        - Alerting
      implementation: []
      references:
        samm2:
          - O-IM-A-2
        iso27001-2017:
          - Not explicitly covered by ISO 27001 - too specific
          - 12.4.1
        iso27001-2022:
          - Not explicitly covered by ISO 27001 - too specific
          - 8.15
      isImplemented: false
      evidence: ""
      comments: ""
    Logging of security events:
      uuid: ccfdd0a8-991e-4269-ad77-c0a54ca655cb
      description: |
        Implement logging of security relevant events. The following events tend to be security relevant:
          - successful/failed login/logout
          - creation, change, and deletion of users
          - errors during input validation and output creation
          - exceptions and errors with security in their name
          - transactions of value (e.g., financial transactions, costly operations)
          - :unicorn: (special things of your application)
      measure:
        Security-relevant events like login/logout or creation, change, deletion
        of users should be logged.
      assessment: |
        - Show which events are logged.
        - Show a test for one event logging.
      difficultyOfImplementation:
        knowledge: 1
        time: 1
        resources: 1
      usefulness: 4
      level: 2
      credits: |
        [AppSecure-nrw](https://github.com/AppSecure-nrw/security-belts/blob/master/orange/logging-of-security-events.md)
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/logstash
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/fluentd
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/bash
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-logging-cheats
      references:
        samm2:
          - O-IM-A-1
        iso27001-2017:
          - 12.4.1
        iso27001-2022:
          - 8.15
      risk: |-
        * No track of security-relevant events makes it harder to analyze an incident.
        * Security incident analysis takes significantly less time with proper security events, such that an attack can be stopped before the attacker reaches his goal.
      isImplemented: false
      evidence: ""
      comments: ""
    PII logging concept:
      uuid: 613a73dc-4f60-49db-a6ce-4fb7bf8519f9
      risk:
        Personal identifiable information (PII) is logged and the privacy law (e.g. General Data Protection Regulation)
        is not followed.
      measure: A concept how to log PII is documented and applied.
      difficultyOfImplementation:
        knowledge: 1
        time: 1
        resources: 1
      usefulness: 1
      level: 5
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/rsyslog
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/logstash
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/fluentd
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/bash
      references:
        samm2:
          - O-OM-A-1
        iso27001-2017:
          - Not explicitly covered by ISO 27001 - too specific
          - 12.4.1
          - 18.1.1
        iso27001-2022:
          - Not explicitly covered by ISO 27001 - too specific
          - 8.15
          - 5.31
      isImplemented: false
      evidence: ""
      comments: ""
    Visualized logging:
      uuid: 7c735089-6a83-419f-8b27-c1e676cedea1
      risk:
        System and application protocols are not visualized properly which leads
        to no or very limited logging assessment. Specially developers might have
        difficulty to read applications logs with unusually tools like the Linux tool
        'cat'
      measure:
        Protocols are visualized in a simple to use real time monitoring system.
        The GUI gives the ability to search for special attributes in the protocol.
      difficultyOfImplementation:
        knowledge: 1
        time: 3
        resources: 3
      usefulness: 4
      level: 2
      dependsOn:
        - Centralized system logging
        - Centralized application logging
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/elk-stack
      references:
        samm2:
          - O-IM-A-1
        iso27001-2017:
          - Not explicitly covered by ISO 27001 - too specific
          - 12.4.1
        iso27001-2022:
          - Not explicitly covered by ISO 27001 - too specific
          - 8.15
      isImplemented: false
      evidence: ""
      comments: ""
    Analyze logs:
      uuid: b217c8bb-5d61-4b41-a675-1083993f83b1
      risk: Not aware of attacks happening.
      measure: Check logs for keywords.
      difficultyOfImplementation:
        knowledge: 2
        time: 2
        resources: 2
      usefulness: 3
      level: 3
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/sigmahq
      references:
        samm2:
          - O-IM-A-1
        iso27001-2017:
          - ISO 27001:2017 mapping is missing
        iso27001-2022:
          - ISO 27001:2022 mapping is missing
